default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: URL_sort_deepak
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: URL_sort_deepak_test
  pool: 5
  username: postgres
  password: postgres